apiVersion: batch/v1
kind: Job
metadata:
  name: optuna
  namespace: evaluation
  labels:
    app: optuna
spec:
  template:
    metadata:
      labels:
        app: optuna
    spec:
      containers:
      - name: optuna
        image: gaocegege/optuna-tf-example:v1.0.0
        command:
        - python
        - optuna-local.py
        - "10"
      restartPolicy: OnFailure