apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: evaluation
  name: katib-distributed-example
spec:
  parallelTrialCount: 10
  maxTrialCount: 150
  maxFailedTrialCount: 150
  objective:
    type: minimize
    goal: 0
    objectiveMetricName: entropy
  algorithm:
    algorithmName: random
  parameters:
    - name: --units
      parameterType: int
      feasibleSpace:
        min: "0"
        max: "1024"
    - name: --dropout
      parameterType: double
      feasibleSpace:
        min: "0"
        max: "1"
    - name: --optimizer
      parameterType: categorical
      feasibleSpace:
        list:
        - "adam"
        - "sgd"
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: "kubeflow.org/v1"
          kind: TFJob
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
           tfReplicaSpecs:
            PS:
              replicas: 1
              restartPolicy: Never
              template:
                metadata:
                  labels:
                    chaos: enabled
                spec:
                  containers:
                    - name: tensorflow
                      image: gaocegege/katib-tf-example:v1.0.0
                      resources:
                        limit:
                          cpu: 500m
                          memory: 500Mi
                        requests:
                          cpu: 100m
                          memory: 100Mi
                      command:
                        - "python"
                        - "/katib-ps-worker.py"
                        - "--train_steps"
                        - "5000"
                        {{- with .HyperParameters}}
                        {{- range .}}
                        - "{{.Name}}={{.Value}}"
                        {{- end}}
                        {{- end}}
            Worker:
              replicas: 2
              restartPolicy: Never
              template:
                metadata:
                  labels:
                    chaos: enabled
                spec:
                  containers:
                    - name: tensorflow
                      image: gaocegege/katib-tf-example:v1.0.0
                      resources:
                        limit:
                          cpu: 500m
                          memory: 500Mi
                        requests:
                          cpu: 100m
                          memory: 100Mi
                      command:
                        - "python"
                        - "/katib-ps-worker.py"
                        - "--train_steps"
                        - "5000"
                        {{- with .HyperParameters}}
                        {{- range .}}
                        - "{{.Name}}={{.Value}}"
                        {{- end}}
                        {{- end}}