apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: chaos-testing
spec:
  action: pod-failure
  duration: 5m
  selector:
    namespaces:
      - evaluation
    labelSelectors:
      chaos: enabled
  scheduler:
    cron: "@every 10m"
  mode: fixed-percent
  value: "100"
